# Generated by Django 3.0.6 on 2020-05-21 16:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_profile_gender'),
    ]

    operations = [
        migrations.CreateModel(
            name='Diet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Food',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=20)),
                ('type', models.CharField(choices=[('m', 'Meat'), ('v', 'Vegetables'), ('ve', 'Vegan'), ('F', 'Fruit')], max_length=10)),
                ('calories', models.FloatField(blank=True, null=True)),
                ('fat', models.FloatField(blank=True, null=True)),
                ('carbs', models.FloatField(blank=True, null=True)),
                ('protein', models.FloatField(blank=True, null=True)),
                ('note', models.CharField(blank=True, max_length=40)),
            ],
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='Age',
            new_name='age',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='BMI',
            new_name='bmi',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='Height',
            new_name='height',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='Weight',
            new_name='weight',
        ),
        migrations.CreateModel(
            name='Meal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=20)),
                ('type', models.CharField(choices=[('b', 'Breakfast'), ('l', 'Lunch'), ('d', 'Dinner'), ('s', 'Snack')], max_length=8)),
                ('diet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Diet')),
                ('foods', models.ManyToManyField(to='core.Food')),
            ],
        ),
        migrations.AddField(
            model_name='diet',
            name='Profile',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='core.Profile'),
        ),
    ]
