# Generated by Django 3.0.6 on 2020-05-21 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20200521_1632'),
    ]

    operations = [
        migrations.AddField(
            model_name='diet',
            name='photo',
            field=models.ImageField(default='', upload_to='Diet'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='food',
            name='photo',
            field=models.ImageField(default='', upload_to='Food'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='meal',
            name='photo',
            field=models.ImageField(default='', upload_to='Meal'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='photo',
            field=models.ImageField(default='', upload_to='Profile'),
            preserve_default=False,
        ),
    ]
