# Generated by Django 3.0.6 on 2020-06-17 22:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20200609_1801'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='diet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Diet'),
        ),
    ]
