# Generated by Django 3.0.6 on 2020-06-18 02:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20200617_2201'),
    ]

    operations = [
        migrations.AddField(
            model_name='diet',
            name='description',
            field=models.CharField(blank=True, max_length=40),
        ),
    ]
